### PR TITLE
Alphabetized search results.

### PR DESCRIPTION
**Pull request by cacciatc**
Also now alphabetizing a user's package on the user page.

### CODE REVIEW

**Comment by ddevault** [comment]
I kind of liked it better when search results were ordered by date updated.

**Comment by cacciatc** [comment]
Understandable. Just familiarizing myself with the codebase while tackling low-hanging fruit on the issue-tracker :)

**Comment by ddevault** [comment]
Seems fair. How about adding a dropdown to change the sort order?

**Comment by cacciatc** [comment]
That sounds good. Closing this PR then, so I can create a feature branch, work, and PR from there.

Perhaps an update of https://github.com/KnightOS/KnightOS/issues/257 would be good too.

**Comment by ddevault** [comment]
Got it. Also, for the record, the changes you've made here would only alpha sort the current page of results, but the pages themselves would be in the same order. You'll want to sort in the sqlalchemy level in the backend.

**Comment by cacciatc** [comment]
Doh! Wasn't thinking. Will do.

**Pull request closed without merging**
